# azure-pipelines.yml

trigger:
- main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'   # choose your Python version
    addToPath: true

# Step 2: Install dependencies (if requirements.txt exists)
- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  displayName: 'Install dependencies'

# Step 3: Run hello.py
- script: |
    python hello.py
  displayName: 'Run hello.py'
