trigger:
  branches:
    include:
      - main

pool:
  name: Default   # <-- your agent pool name

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  displayName: 'Install Python dependencies'

- script: python hello.py
  displayName: 'Run hello.py'
